auth_enabled: false
server:
  http_listen_port: 3100
common:
  instance_addr: 127.0.0.1
  path_prefix: /loki
  storage:
    filesystem:
      chunks_directory: /loki/chunks
      rules_directory: /loki/rules
  replication_factor: 1
  ring:
    kvstore:
      store: inmemory
schema_config:
  configs:
    - from: "2026-01-01"
      store: tsdb
      object_store: filesystem
      schema: v13
      index:
        prefix: index_
        period: 24h
compactor:
  working_directory: /loki/compactor
  compaction_interval: 10m
  retention_enabled: true
  retention_delete_delay: 2h
  retention_delete_worker_count: 2
  delete_request_store: filesystem
limits_config:
  retention_period: 168h
  max_query_parallelism: 2
  split_queries_by_interval: 1h
  ingestion_rate_mb: 1
  ingestion_burst_size_mb: 2
  max_global_streams_per_user: 1000
query_range:
  results_cache:
    cache:
      embedded_cache:
        enabled: false
querier:
  max_concurrent: 2
analytics:
  reporting_enabled: false
